name: OLEC
options:
  bundleIdPrefix: com.olec
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "14.0"
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    SWIFT_VERSION: 5.0

targets:
  OLEC:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.olec.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: 1 # iPhone only
        ENABLE_BITCODE: NO
        SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: OLEC
        CFBundleDisplayName: OLEC
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSLocationWhenInUseUsageDescription: OLEC needs your location to find events near you
        NSLocationAlwaysAndWhenInUseUsageDescription: OLEC needs your location to find events near you and provide real-time updates
        NSCameraUsageDescription: OLEC needs camera access to let you take photos for events and profile pictures
        NSPhotoLibraryUsageDescription: OLEC needs photo library access to let you choose photos for events and profile pictures
        UIBackgroundModes:
          - location
          - remote-notification
    dependencies:
      - framework: MapKit.framework
      - framework: CoreLocation.framework
      - sdk: CoreData.framework
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseMessaging

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0 